export interface IOrder {
  id: number,
  number: string,
  status: number,
  userId: number,
  addressBookId: number,
  orderTime: Date | string,
  checkoutTime: Date | string,
  payMethod: number,
  payStatus: number,
  amount: number,
  remark: string,
  phone: string,
  address: string,
  userName: string,
  consignee: string,
  cancelReason: string,
  rejectionReason: string,
  cancelTime: Date | string,
  estimatedDeliveryTime: Date | string,
  deliveryStatus: number,
  deliveryTime: Date | string,
  packAmount: number,
  tablewareNumber: number,
  tablewareStatus: number,
}

export interface IOrderDetail {
  id: number,
  name: string,
  image: string,
  orderId: number,
  dishId: number,
  setmealId: number,
  dishFlavor: string,
  number: number,
  amount: number,
}